wandb_version: 1

test:
  desc: null
  value: AAA
_wandb:
  desc: null
  value:
    python_version: 3.9.1
    cli_version: 0.14.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681516975.716885
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.1
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
